name: Check JSON file

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install jsonlint
        run: npm install jsonlint -g
      - name: Check livechart-raw-data.json
        run: jsonlint -q livechart-raw-data.json
